### ISSUE TITLE
Implement mobile nav bar

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#1073]
### Open Questions/To-dos

- @mj-hof in Figma the context area is collapsed in a 3 dot menu but they are still some icons (notification/search) displayed in the nav bar itself. Does this make sense? The context menu content is up to the project so can not really differentiate here, should we just move the whole context are to the 3 dot menu?
    - create new slot (something like "contextAreaMobile") that will remain in the nav bar even on mobile
    - content of contentArea slot will move to the 3 dot menu on mobile
- @mj-hof Is the logo not visible at all on mobile? Answer:
    - also show logo (so we can just reuse the OnyxNavAppArea component) if its given by the project

### Depends on

- #995

### Why?

The nav bar should be responsive and adapt on mobile breakpoints.

### Design

[Figma link](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=4581-12707&t=I3lGGbSfMeUXKaYW-4).

### Acceptance criteria

- [x] the design is implemented
- [x] when reaching `xs` breakpoint or smaller, the nav bar should switch to the mobile layout
- [x] when burger menu is open: app area (app name + logo is shown instead of active page name)
- [x] if a page is active and burger menu is closed, the active page name is displayed, otherwise the app name
- [x] the context area collapses into a "3 dot menu"
- [x] the nav items collapse into a burger menu

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Set task to `In Approval`

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/story/navigation-navbar--with-context-area&globals=viewport:sm)
- [x] approved by designer @mj-hof 
- [x] approved by dev @BoppLi 

### Implementation details

- if possible prefer a CSS implementation
- use container queries instead of media queries so the component behaves correctly also when e.g. displayed inside Storybook (and use our [container query utils](https://onyx.schwarz/development/breakpoints.html#container-queries))
- prevent cloning DOM nodes

#### Applicable ARIA Pattern

[Menu button](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/)

**Comment by BoppLi** [comment]
Approval feedback @larsrickert 

1. could you create a follow up ticket for smoother open/close animations, if it doesn't exist already?
2. when testing it in the alpha app, I noticed that the menu does not close after navigating to another page. is this to be done on "project side", if so, could you add this to the alpha app's nav bar? or is this a feature we should take care of, e.g. with an mobileOpen prop?
3. in the [Storybook link](https://storybook.onyx.schwarz/?path=/story/navigation-navbar--with-context-area&globals=viewport:sm) you created above, the example does not fire any events when clicking on nav items. is this intentional / out of scope?

**Comment by BoppLi** [comment]
2) could you add that property and connect it in the alpha app? imho the UX is not the best when it just stays open
