### ISSUE TITLE
Adjust selected text contrast in dark mode

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1366]
Currently it is hard to detect which text is selected in input controls like OnyxInput, OnyxTextarea, OnyxSelect when darkmode is active:
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/bcba9ac8-80f4-4f17-a18e-4cba7fa34aeb)

The currently used token is `--onyx-color-base-neutral-200`

Info: **text color** as well as background color can be adjusted however you like.
https://developer.mozilla.org/en-US/docs/Web/CSS/::selection
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/599a505e-f7ce-41ab-b0fa-7b8df7b24d90)

**Comment by jannick-ux** [comment]
In the figma library the default color 500 is used with an opacity of .30 (in darkmode) and .20 (in light mode).
Do we have to alignhere? Or what works best for dev?

**Comment by jannick-ux** [comment]
Update: After a discussion in the onyx daily we detected, that this problem is only in read-only and disabled state. We decided to use the same marking color like with the default state (primary). Screenshot below.


![Image](https://github.com/user-attachments/assets/a78906fa-7bcb-41eb-8ff5-87e0a75df1f1)
![Image](https://github.com/user-attachments/assets/6b31f1ee-1b78-4234-b167-ffe7920b11b7)
