### ISSUE TITLE
Fix skeleton prop injection for OnyxRadioGroup

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#1967]
- [x] Fix skeleton prop injection for `OnyxRadioGroup`
 - when there are no (yet) options given and skeleton is injected `true`, the radiogroup
- [x] Add OnyxPageLayout example

**Comment by larsrickert** [comment]
Does it also make sense to let the user provide the skeleton in any component to turn all child components in skeleton?
Example:

- you have a page with 3 sections
- the user wants to make the 2nd section skeleton but not the others
- currently this would not work because its only possible on page or form level, but the 2nd section might not be a form

**Comment by JoCa96** [comment]
We can add instructions on how to use the inject

**Comment by MajaZarkova** [comment]
follow up tickets: #2015 #2016
