### ISSUE TITLE
[Bug]: Recent addition of skeleton symbols broke input components

### ISSUE THREAD

**Issue by r0bin** [SchwarzIT/onyx#1980]
### Version

sit-onyx@1.0.0-beta.55

### Description

It seems that #1938 broke components that handle input, like `OnyxInput`, `OnyxButton`, `OnyxStepper` and probably some more, throwing a very unhelpful error message from Vue:

```
Uncaught TypeError: Cannot convert a Symbol value to a string
    at styleValue (runtime-core.esm-bundler.js:4403:5)
    at getInvalidTypeMessage (runtime-core.esm-bundler.js:4386:25)
    at validateProp (runtime-core.esm-bundler.js:4345:14)
    at validateProps (runtime-core.esm-bundler.js:4317:5)
    at initProps (runtime-core.esm-bundler.js:4018:5)
    at setupComponent (runtime-core.esm-bundler.js:7829:3)
    at mountComponent (runtime-core.esm-bundler.js:5179:7)
    at processComponent (runtime-core.esm-bundler.js:5145:9)
    at patch (runtime-core.esm-bundler.js:4663:11)
    at mountChildren (runtime-core.esm-bundler.js:4895:7)
```

### Reproduction steps

1. install `sit-onyx@1.0.0-beta.55`
2. add a `<OnyxInput />` to your template

### Confirmations

- [X] I have checked that there is not already a bug report for my issue.
- [X] I confirm that are no sensitive information included in this bug report. e.g. credentials, internal project details (for employees of the Schwarz Group) etc.

**Comment by JoCa96** [comment]
Seems only to happen in `DEV` mode, as a temporary workaround you can set `isProduction` of the [vue vite plugin](https://www.npmjs.com/package/@vitejs/plugin-vue) to true.

**Comment by JoCa96** [comment]
Vue infers the type incorrectly:
<img width="1309" alt="Screenshot 2024-10-21 at 09 04 51" src="https://github.com/user-attachments/assets/49245148-dbad-4174-bc9f-b90fcc6ccae4">

[Playground](https://play.vuejs.org/#__PROD__eNp9Uk2L2zAQ/StClzgQbNptL6mT0rQ5tHSbpQmUgqB47XHirSwJSU4cUv/3juSP9YbdBR2kN2/evJnRhX5SKjxWQOc0NqkulCUGbKWWTBSlktqSC9GQk4bkWpZkgtTJEPosS9XhYeQeTmnygYk4arVQBR8WSsUTC/giJPZJEd7jaBSgM2pNKkVe7MMHIwX6uTg6oynyCw56o2whhWF0TnzExRLO5embx6yuYNbj6QHSv8/gD6Z2GKN3GgzoIzA6xGyi92Db8Hr7A2q8D8FSZhVH9ivBn2Akr5zHlraqRIa2Rzzv9qsfXSH2O7OuLQjTN+WMOmbj+YziKN2oXmr90e5N+M7nMdHgFPs1XC+U8ETsF5iHMuPlnhKbHtZ5Dqntl+xrM4p7HFjb37erzfcZ2Z7Le8k3eiUlh0T0wJ2WakZ+6UQp0I8yYaQwgAVRigncrrHEI2RBToU9fIE8qbg1QQZ5IcCpmNh3WBY1ZB/n1/VQp1kG0xk68gwkeGOkmfoSo2aCYEoWS+KKYmrI5T7wpUOfOJ2+/kmz4ugvhCQmc8ejUQtff9xW1xocOdR+YG2rnbdF10XA6O25vTLq/HZke1YwmiPyHSLzLv9Z4jCRQd2n/iP3w6DGSd1m4t0S+bsnNPT/5wjafUP0fxO+D9+8pc1/FLBkWw==)

**Comment by JoCa96** [comment]
**Background:**
1. Vue Prop Runtime Validation Vue validates prop types at runtime (e.g., `typeof prop === "boolean"`). If a prop doesn't pass the validation, an error is logged (only in DEV mode): `Invalid prop: type check failed for prop "${name}". Expected ${expectedTypes}.`

1. Vue Prop Type inference Vue supports different ways to define the types of props, which are used for the runtime validation. We define the props using [type-based declaration](https://vuejs.org/guide/typescript/composition-api.html#typing-component-props). This means that the runtime types are inferred based on the typescript types.

**Cause:**
In our case, Vue's compiler inferred the prop type used for runtime validation as `Boolean`, even though the typescript type is `typeof unique symbol | boolean`. This causes the runtime validation to fail and trying to log an error. Because Vue tries to create an error message using implicit string conversions and symbols cannot be implicitly [converted to a string,](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toString#description) the JS runtime throws: `Uncaught (in promise) TypeError: can't convert symbol to string`

**Fix**
Replaced all prop uses of `typeof <unique symbol>` with just `symbol`, this fixes the type inference and the runtime validation. Follow-up issues for Vue core will be created.

**Comment by JoCa96** [comment]
Vue Bug is tracked at https://github.com/vuejs/core/issues/12234
