### ISSUE TITLE
Implement support search for components

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#287]
Currently the VitePress docs uses local search which means that all static content is indexed during build-time.
But since the components and their properties/events etc. are only embedded from Storybook using an iframe, their data is not available for the search.

We could use some 3rd party search crawler like Algolia which is natively supported by VitePress and commonly used in documentations like Vue.js, Vite etc.: https://vitepress.dev/reference/default-theme-search

We should check the license and pricing of it. Usually Algolia is free for Open Source projects by should double check this.

### Why?

_Currently the VitePress docs uses local search which means that all static content is indexed during build-time.
But since the components and their properties/events etc. are only embedded from Storybook using an iframe, their data is not available for the search._

### Acceptance criteria

- [ ] The components can be searched by their name + data (properties/events)

### Definition of Done

- [ ] we can search dynamically added components
- [ ] follow up tickets were created if necessary
- [ ] updated version + documentation is deployed
- [ ] Storybook can show the feature

**Review**
- add link to deployed storybook
- add link to deployed docs
- [ ] approved by designer _add designer tag_
- [ ] approved by dev _add dev tag_
  

### Implementation details

Check the explanation in the previous comment

#### Reference implementations

- https://vitepress.dev/reference/default-theme-search

**Comment by MajaZarkova** [comment]
### Why?

_Currently the VitePress docs uses local search which means that all static content is indexed during build-time.
But since the components and their properties/events etc. are only embedded from Storybook using an iframe, their data is not available for the search._


### Definition of Done

- [ ] we can search dynamically added components
- [ ] follow up tickets were created if necessary
- [ ] updated version + documentation is deployed
- [ ] Storybook can show the feature
- [ ] Set task to `In review`


**Review**
    -  _add link to deployed storybook_
    - _add link to deployed docs_
    - [ ] approved by designer _add designer tag_
    - [ ] approved by dev _add dev tag_
  

### Implementation details

Check the explanation in the previous comment

#### Reference implementations

- https://vitepress.dev/reference/default-theme-search

**Comment by mj-hof** [comment]
Take into consideration after documentation workshop

**Comment by larsrickert** [comment]
Closed as no longer needed due to #955.
If needed: we can make a community poll to check how easy they can search the content and check if we need to change anything
