### ISSUE TITLE
Investigate Storybook intersection prop types issue

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#290]
Investigate if we are able to provide a fix for https://github.com/storybookjs/storybook/issues/25582.

**Comment by larsrickert** [comment]
This issue will be fixed by the open PR https://github.com/storybookjs/storybook/pull/22285

We can already use a canary release by changing our Storybook version to `0.0.0-pr-22285-sha-d60d546d` but I tested it out, there are still some minor bugs.

The main issue with the intersection property types are fixed :)
