### ISSUE TITLE
Concept tab bar

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#438]

**Comment by jannick-ux** [comment]
some things need to be added in the figma component:

- [ ] skeleton state
- [ ] text property for the headlines

this need to be changed:

- [ ] the default component should not show any of the focus states. Those should only be accessed by clicking on it manually

**Comment by jannick-ux** [comment]
updated review:

Please add
- [ ] icons as a boolean inside the tabbutton (left to the label)
- [ ] documentation for the guidelines of the behavior (e.g. horizontal scrolling on small windows; the option to set the tabbutton width to "fill" if needed; definition of the microanimation of the affected content)
- [ ] more tabs to the main component and give all of them a boolean property called "tab1, tab2, etc.

Please remove
- [ ] the "n"-counter in the headline, so that it has a better designers-experience when highlighting the text. Just use "Tab" for the placeholdertext

Please change:
- [ ] the name of the rectangle inside of the "wrapper highlight"
- [ ] the name of the main component into "TabBar"
- [ ] the hight of the "wrapper highlight rectangle" to  2px instead of 4px
