### ISSUE TITLE
Implement success state for OnyxFormElement

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#573]
### Depends on

- #189

### Why?

There are cases where it is necessary to communicate an explicit `success` state for an FormElement:
- To highlight the validity of important inputs (E.g., a password input on sign-up)
- To show validity after an asynchronous validation (E.g. Chosen username is available).
- To show the successful execution of an action related to the input (E.g., Value copied to the clipboard)

The (validation) `valid` state independent of the `success` state:
- the `success` state is set explicitly and **not** the implicit result of validation
- the validation `error` state has higher priority than the `success`
- the `success` state does not change or affect the validation
- for now only support for inputs (text, select) and not for textarea

### Design

https://www.figma.com/design/EBi98T51T9fGfjrYYfsulg/onyx---Archive?node-id=3427-73120&t=WFV3kII28sKTTZft-4

### Acceptance criteria
- [x] A new type `FormMessage` is created
- [x] `message`, `successMessage`, `errorMessage` all use the new type
    -  * Message precedence from highest to lowest:
      1. `errorMessage`
      2. html native validation error message
      3. `successMessage`
      4. `message`
- [x] when `successMessage` is shown, a green checkmark symbol is shown on the right -> Follow up #2143 
- [x] All existing components that use the `OnyxFormElement` are extended to support the new API
- [x] Follow-up from #1731: Refactor to only show `onyx-form-element__footer` when any message is shown: Right now the gap is from the parent is applied even when no message is visible

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Review**

- [Input](https://storybook.onyx.schwarz/?path=/story/form-elements-input--success-input)
- [Textarea](https://storybook.onyx.schwarz/?path=/story/form-elements-textarea--success-message)
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96 

### Implementation details

_Consider that success might be shown without message, but error should never be shown without message. Also, do we still need a message for a11y reasons?_ 

```ts
/**
  * If it's just a string it acts as `FormErrorMessage.shortMessage`
  */
export type FormErrorMessage = string | {
  /**
   * A short error message preview that is shown permanently beneath the input field
   */
  shortMessage: string;
  /**
   * An extended message that is shown temporarily after hovering over the message tooltip.
   */
  longMessage?: string;
};
```
```ts

/**
  * Message precedence from highest to lowest:
  * 1. `errorMessage`
  * 2. html native validaiton error message
  * 3. `successMessage`
  * 4. `message`
  */
export type OnyxFormElementProps = {
  // Refactor the messages to take the same format:
  successMessage?: FormErrorMessage;
  errorMessage?: FormErrorMessage;
  message?: FormErrorMessage;
}
```

**Comment by mj-hof** [comment]
@jannick-ux Open questions:
- What's the use case behind that success/valid state?
- Do we need the "copy"-button? Misleading user interactive?
- What about text area, selection controls - do they have a valid/success state as well?

**Comment by jannick-ux** [comment]
- The success state can be used for forms that need to be validated (e.g. the user needs to fill out his personal data and the system checks, if the username could be validated). It is a completely optional thing for concepting, although it could be really handy in some usecases. So I created it as an optional addition. 
- The copy icon is optional as well. It gives the opportunity to copy the content with one single click. I got the request of this features from several sources. Why do you think it is misleading?
- Selection controls don't have text area because the "success indicator" validates an input, but not a binary choise. 
Text areas have no success state as well, because of their purpose. They aren't used for inputs that can be correct or incorrect (like the OnyxInput does). The have the purpose to insert continuous text (that can be formatted). Continuous text cannot be valid or invalid.

**Comment by JoCa96** [comment]
Story was split and "Copy action" is moved to #1887
