### ISSUE TITLE
Implement table scrolling

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#840]
### Depends on

- #837 

### Design

[Figma](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=1967%3A33522&mode=dev)

### Acceptance criteria

- The header sticks to the top of the scroll-area:
  - [x] When the height of the table is restricted by the user (e.g., `max-height` is set on the `onyx-table`) the table should have a scroll bar
  - [x] When the page is scrolled, with the table on it
- [x] Must not be hidden under the top-bar
- [x] Update/tokenize column hover + update screenshot `packages/sit-onyx/playwright/snapshots/components/OnyxTable/Table-scrolling--chromium-linux.png`
   https://github.com/SchwarzIT/onyx/pull/1200/files/e8ea399feba859cb36ca5a71b6498241db7dbaef#r1623901045

### Definition of Done

- [x] The following component requirements are implemented:
  - [x] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
  - #1209 
  - #1225 
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Storybook: overflow y](https://storybook.onyx.schwarz/?path=/story/components-table--limited-width)
- [Storybook: both axis scrollable](https://storybook.onyx.schwarz/?path=/story/components-table--limited-height-and-width)
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Implementation details

Ideally, this is implemented without the user having to set anything besides a `max-height` on the `onyx-table` itself.
If otherwise not possible, we can add a new property, which sets a CSS class to the `onyx-table`.

- https://developer.mozilla.org/en-US/docs/Web/CSS/position

#### Reference implementations

- [Kendo UI](https://docs.telerik.com/kendo-ui/controls/grid/overview)
- [AG Grid](https://www.ag-grid.com/vue-data-grid/deep-dive/#create-a-basic-grid) 

#### Applicable ARIA Pattern

[Table](https://www.w3.org/WAI/ARIA/apg/patterns/table/)

**Comment by BoppLi** [comment]
We got into issues with the column hover  in combination with scrolling (because of the sticky header). the result is, that we have to use a low opacity overlay for column hover instead of defined colors which would completely cover the text instead.

The defined colors were
- row hover color in light: --onyx-color-themed-neutral-200: #e3eaf0;
- row hover color in dark: --onyx-color-themed-neutral-1000: #11212d;

So we now need new transparent color tokens for this use case, my suggestion for now is:

- NEW column hover opaque in light:  #26628d30;
- NEW column hover opaque in dark:  #2e425230;

you can see the current effect in the following screenshots. USUALLY the user can't hover row and column on the same time, In this case I forced the double hover with the dev tools for comparing.
see the cell "apple" with row hover, and the cell "3.75" with opaque column hover (the 1.99 effect won't appear in nature.)
 
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/a2a1a907-48d6-4b48-ba7b-97698ec07cfa)
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/f8773e41-af26-4765-acdd-e8f5499954b0)

**Comment by BoppLi** [comment]
Idea from Lars regarding the tokens: https://github.com/SchwarzIT/onyx/pull/1200#discussion_r1621923714

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/ce5f9783-d74b-46d8-b77a-d7dd9dcfa771)

**Comment by BoppLi** [comment]
> You could take the token neutral/500 and give it an opacity of 10%. Then the same color comes out for the table hover. In dark mode, the opacity doesn't work as desired. I don't have a solution yet

-> for dark mode, keep the current value. the ticket #1209 stays open for now
